/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ImportsRouteImport } from './routes/imports'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as ChargersRouteImport } from './routes/chargers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LaptopsIndexRouteImport } from './routes/laptops.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as LaptopsNewRouteImport } from './routes/laptops.new'
import { Route as LaptopsIdRouteImport } from './routes/laptops.$id'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as CustomersIdIndexRouteImport } from './routes/customers.$id.index'
import { Route as CustomersIdEditRouteImport } from './routes/customers.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsRoute = ImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargersRoute = ChargersRouteImport.update({
  id: '/chargers',
  path: '/chargers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaptopsIndexRoute = LaptopsIndexRouteImport.update({
  id: '/laptops/',
  path: '/laptops/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaptopsNewRoute = LaptopsNewRouteImport.update({
  id: '/laptops/new',
  path: '/laptops/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LaptopsIdRoute = LaptopsIdRouteImport.update({
  id: '/laptops/$id',
  path: '/laptops/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdIndexRoute = CustomersIdIndexRouteImport.update({
  id: '/customers/$id/',
  path: '/customers/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdEditRoute = CustomersIdEditRouteImport.update({
  id: '/customers/$id/edit',
  path: '/customers/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chargers': typeof ChargersRoute
  '/exports': typeof ExportsRoute
  '/imports': typeof ImportsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/customers/new': typeof CustomersNewRoute
  '/laptops/$id': typeof LaptopsIdRoute
  '/laptops/new': typeof LaptopsNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/laptops/': typeof LaptopsIndexRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/customers/$id/': typeof CustomersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chargers': typeof ChargersRoute
  '/exports': typeof ExportsRoute
  '/imports': typeof ImportsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/customers/new': typeof CustomersNewRoute
  '/laptops/$id': typeof LaptopsIdRoute
  '/laptops/new': typeof LaptopsNewRoute
  '/customers': typeof CustomersIndexRoute
  '/laptops': typeof LaptopsIndexRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/customers/$id': typeof CustomersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chargers': typeof ChargersRoute
  '/exports': typeof ExportsRoute
  '/imports': typeof ImportsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/customers/new': typeof CustomersNewRoute
  '/laptops/$id': typeof LaptopsIdRoute
  '/laptops/new': typeof LaptopsNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/laptops/': typeof LaptopsIndexRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/customers/$id/': typeof CustomersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chargers'
    | '/exports'
    | '/imports'
    | '/inventory'
    | '/login'
    | '/notifications'
    | '/orders'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/customers/new'
    | '/laptops/$id'
    | '/laptops/new'
    | '/customers/'
    | '/laptops/'
    | '/customers/$id/edit'
    | '/customers/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chargers'
    | '/exports'
    | '/imports'
    | '/inventory'
    | '/login'
    | '/notifications'
    | '/orders'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/customers/new'
    | '/laptops/$id'
    | '/laptops/new'
    | '/customers'
    | '/laptops'
    | '/customers/$id/edit'
    | '/customers/$id'
  id:
    | '__root__'
    | '/'
    | '/chargers'
    | '/exports'
    | '/imports'
    | '/inventory'
    | '/login'
    | '/notifications'
    | '/orders'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/customers/new'
    | '/laptops/$id'
    | '/laptops/new'
    | '/customers/'
    | '/laptops/'
    | '/customers/$id/edit'
    | '/customers/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChargersRoute: typeof ChargersRoute
  ExportsRoute: typeof ExportsRoute
  ImportsRoute: typeof ImportsRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  CustomersNewRoute: typeof CustomersNewRoute
  LaptopsIdRoute: typeof LaptopsIdRoute
  LaptopsNewRoute: typeof LaptopsNewRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  LaptopsIndexRoute: typeof LaptopsIndexRoute
  CustomersIdEditRoute: typeof CustomersIdEditRoute
  CustomersIdIndexRoute: typeof CustomersIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports': {
      id: '/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chargers': {
      id: '/chargers'
      path: '/chargers'
      fullPath: '/chargers'
      preLoaderRoute: typeof ChargersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laptops/': {
      id: '/laptops/'
      path: '/laptops'
      fullPath: '/laptops/'
      preLoaderRoute: typeof LaptopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laptops/new': {
      id: '/laptops/new'
      path: '/laptops/new'
      fullPath: '/laptops/new'
      preLoaderRoute: typeof LaptopsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laptops/$id': {
      id: '/laptops/$id'
      path: '/laptops/$id'
      fullPath: '/laptops/$id'
      preLoaderRoute: typeof LaptopsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id/': {
      id: '/customers/$id/'
      path: '/customers/$id'
      fullPath: '/customers/$id/'
      preLoaderRoute: typeof CustomersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id/edit': {
      id: '/customers/$id/edit'
      path: '/customers/$id/edit'
      fullPath: '/customers/$id/edit'
      preLoaderRoute: typeof CustomersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChargersRoute: ChargersRoute,
  ExportsRoute: ExportsRoute,
  ImportsRoute: ImportsRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  CustomersNewRoute: CustomersNewRoute,
  LaptopsIdRoute: LaptopsIdRoute,
  LaptopsNewRoute: LaptopsNewRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  LaptopsIndexRoute: LaptopsIndexRoute,
  CustomersIdEditRoute: CustomersIdEditRoute,
  CustomersIdIndexRoute: CustomersIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
